name: pong-by-yesser-studios
version: '0.0.1'
# ^ this will be changed by the GitHub action.
grade: devel
# ^ this will also be changed by the GitHub action.
summary: A Pong clone by Yesser Studios
description: |
  This Pong clone has everything you would expect from a Pong clone - two pads and a ball.
  Play it with a keyboard or a gamepad with a friend.

base: core22
confinement: devmode
# ^ this will also be changed by the GitHub action.

parts:
  pong-by-yesser-studios:
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    source: .
    build-packages:
      - dotnet-sdk-8.0
    stage-packages:
      - libicu70
    override-build: |
      cd Pong.Desktop
      dotnet restore
      dotnet publish -p:Platform=Linux -c Release -o $SNAPCRAFT_PART_INSTALL --self-contained --use-current-runtime

apps:
  pong-by-yesser-studios:
    command: Pong.Desktop
